# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.1.1
_src_path: gh:algorandfoundation/algokit-react-frontend-template
author_email: itsapurvasb343@gmail.com
author_name: apurva bardapurkar
preset_name: starter
project_name: algo-frontend

