[algokit]
min_version = "v2.0.0"

[project]
<<<<<<< HEAD
type = "frontend"
name = 'ALGO-frontend'
artifacts = "src/contracts"

[project.run]
build = { commands = ['npm run build'], description = 'Build frontend' }
test = { commands = ['npm run test'], description = 'Run frontend tests' }
=======
type = 'workspace'
projects_root_path = 'projects'

[project.run]
build = ['ALGO-contracts', 'ALGO-frontend']
>>>>>>> 8516c4666f58397b41455b52217f67b535621064
